### PR TITLE
implement a recursive resolution mechanism

### PR DESCRIPTION
**Pull request by lestrrat**

### CODE REVIEW

**Comment by bburtin** [comment]
Thanks for implementing this!  I tested the code, and I believe that it doesn't work in some of my test cases.  I've attached my test file: [expand-test.zip](https://github.com/lestrrat/go-jsref/files/700420/expand-test.zip)

Here's the test output.  Seems like `#/links/0` works, but `#/links/1` and `#/links/2` don't.
```
$ go run expand-test.go
#/links/0/schema -> {"properties":{"mac_address":{"type":"string"}},"required":["mac_address"],"type":"object"}
#/links/0/targetSchema -> {"description":"Virtual Machine properties","properties":{"cluster_name":{"type":"string"},"datacenter_name":{"type":"string"},"guest_id":{"type":"string"},"instance_uuid":{"type":"string"},"mac_address":{"type":"string"},"name":{"type":"string"},"uuid":{"type":"string"}},"required":["mac_address","uuid"],"type":"object"}
#/links/1/targetSchema -> {"items":{"$ref":"#/definitions/virtual_machine"},"type":"array"}
#/links/2/schema -> {"items":{"$ref":"#/definitions/virtual_machine"},"type":"array"}
#/links/2/targetSchema -> {"items":{"$ref":"#/definitions/virtual_machine"},"type":"array"}
```

**Comment by lestrrat** [comment]
@bburtin I fixed what I think to be the problem, but can you please provide me with a minimal test case? doing so will help future users. thanks!

**Comment by bburtin** [comment]
Sure thing.  Let me see if I can get the old code to fail with a simplified version of the hyper schema.

**Comment by lestrrat** [comment]
Alright, everything passed, and I wrote some docs explaining the downsides, so going to merge.

**Comment by bburtin** [comment]
Sweet!  Thanks again for taking the time to implement this.

**Pull request merged**
